version: "2"

linters:
  disable: [ ]
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - gosec
    - misspell
    - revive
    - unconvert

settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  gosec:
    exclude-generated: true
  staticcheck:
    checks:
      - "all"

run:
  concurrency: 4
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

asyncapi: 2.0.0
info:
channels:
