// Test code generated by code-agent (AI agent). DO NOT EDIT MANUALLY.
// Purpose:
// - To increase coverage
//

package gsmmap

import (
	"strings"
	"testing"
)

func TestMarshalErrors(t *testing.T) {
	t.Run("SriSm_InvalidMSISDN", func(t *testing.T) {
		sriSm := &SriSm{
			MSISDN: "INVALID",
		}
		_, err := sriSm.Marshal()
		if err == nil {
			t.Error("Expected error for invalid MSISDN")
		} else if !strings.Contains(err.Error(), "failed to encode MSISDN") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("SriSm_InvalidServiceCentreAddress", func(t *testing.T) {
		sriSm := &SriSm{
			MSISDN:               "12345",
			ServiceCentreAddress: "INVALID",
		}
		_, err := sriSm.Marshal()
		if err == nil {
			t.Error("Expected error for invalid ServiceCentreAddress")
		} else if !strings.Contains(err.Error(), "failed to encode ServiceCentreAddress") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("SriSmResp_InvalidIMSI", func(t *testing.T) {
		resp := &SriSmResp{
			IMSI: "INVALID",
		}
		_, err := resp.Marshal()
		if err == nil {
			t.Error("Expected error for invalid IMSI")
		} else if !strings.Contains(err.Error(), "failed to encode IMSI") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("SriSmResp_InvalidNetworkNodeNumber", func(t *testing.T) {
		resp := &SriSmResp{
			IMSI: "12345",
			LocationInfoWithLMSI: LocationInfoWithLMSI{
				NetworkNodeNumber: "INVALID",
			},
		}
		_, err := resp.Marshal()
		if err == nil {
			t.Error("Expected error for invalid NetworkNodeNumber")
		} else if !strings.Contains(err.Error(), "failed to encode NetworkNodeNumber") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("MtFsm_InvalidIMSI", func(t *testing.T) {
		mtFsm := &MtFsm{
			IMSI: "INVALID",
		}
		_, err := mtFsm.Marshal()
		if err == nil {
			t.Error("Expected error for invalid IMSI")
		} else if !strings.Contains(err.Error(), "failed to encode IMSI") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("MtFsm_InvalidServiceCentreAddressOA", func(t *testing.T) {
		mtFsm := &MtFsm{
			IMSI:                   "12345",
			ServiceCentreAddressOA: "INVALID",
		}
		_, err := mtFsm.Marshal()
		if err == nil {
			t.Error("Expected error for invalid ServiceCentreAddressOA")
		} else if !strings.Contains(err.Error(), "failed to encode ServiceCentreAddressOA") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("MoFsm_InvalidServiceCentreAddressDA", func(t *testing.T) {
		moFsm := &MoFsm{
			ServiceCentreAddressDA: "INVALID",
		}
		_, err := moFsm.Marshal()
		if err == nil {
			t.Error("Expected error for invalid ServiceCentreAddressDA")
		} else if !strings.Contains(err.Error(), "failed to encode ServiceCentreAddressDA") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("MoFsm_InvalidMSISDN", func(t *testing.T) {
		moFsm := &MoFsm{
			ServiceCentreAddressDA: "12345",
			MSISDN:                 "INVALID",
		}
		_, err := moFsm.Marshal()
		if err == nil {
			t.Error("Expected error for invalid MSISDN")
		} else if !strings.Contains(err.Error(), "failed to encode MSISDN") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("UpdateLocation_InvalidIMSI", func(t *testing.T) {
		ul := &UpdateLocation{
			IMSI: "INVALID",
		}
		_, err := ul.Marshal()
		if err == nil {
			t.Error("Expected error for invalid IMSI")
		} else if !strings.Contains(err.Error(), "failed to encode IMSI") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("UpdateLocation_InvalidMSCNumber", func(t *testing.T) {
		ul := &UpdateLocation{
			IMSI:      "12345",
			MSCNumber: "INVALID",
		}
		_, err := ul.Marshal()
		if err == nil {
			t.Error("Expected error for invalid MSCNumber")
		} else if !strings.Contains(err.Error(), "failed to encode MSCNumber") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("UpdateLocation_InvalidVLRNumber", func(t *testing.T) {
		ul := &UpdateLocation{
			IMSI:      "12345",
			MSCNumber: "12345",
			VLRNumber: "INVALID",
		}
		_, err := ul.Marshal()
		if err == nil {
			t.Error("Expected error for invalid VLRNumber")
		} else if !strings.Contains(err.Error(), "failed to encode VLRNumber") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("UpdateGprsLocation_InvalidIMSI", func(t *testing.T) {
		ugl := &UpdateGprsLocation{
			IMSI: "INVALID",
		}
		_, err := ugl.Marshal()
		if err == nil {
			t.Error("Expected error for invalid IMSI")
		} else if !strings.Contains(err.Error(), "failed to encode IMSI") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("UpdateGprsLocation_InvalidSGSNNumber", func(t *testing.T) {
		ugl := &UpdateGprsLocation{
			IMSI:       "12345",
			SGSNNumber: "INVALID",
		}
		_, err := ugl.Marshal()
		if err == nil {
			t.Error("Expected error for invalid SGSNNumber")
		} else if !strings.Contains(err.Error(), "failed to encode SGSNNumber") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("UpdateGprsLocation_InvalidSGSNAddress", func(t *testing.T) {
		ugl := &UpdateGprsLocation{
			IMSI:        "12345",
			SGSNNumber:  "12345",
			SGSNAddress: "INVALID-IP",
		}
		_, err := ugl.Marshal()
		if err == nil {
			t.Error("Expected error for invalid SGSNAddress")
		} else if !strings.Contains(err.Error(), "failed to encode SGSNAddress") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("UpdateLocationRes_InvalidHLRNumber", func(t *testing.T) {
		res := &UpdateLocationRes{
			HLRNumber: "INVALID",
		}
		_, err := res.Marshal()
		if err == nil {
			t.Error("Expected error for invalid HLRNumber")
		} else if !strings.Contains(err.Error(), "failed to encode HLRNumber") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("UpdateGprsLocationRes_InvalidHLRNumber", func(t *testing.T) {
		res := &UpdateGprsLocationRes{
			HLRNumber: "INVALID",
		}
		_, err := res.Marshal()
		if err == nil {
			t.Error("Expected error for invalid HLRNumber")
		} else if !strings.Contains(err.Error(), "failed to encode HLRNumber") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})
}

func TestUpdateLocationMarshal_WithVlrCapability(t *testing.T) {
	ul := &UpdateLocation{
		IMSI:      "123456789012345",
		MSCNumber: "12345",
		VLRNumber: "67890",
		VlrCapability: &VlrCapability{
			SupportedCamelPhases: &SupportedCamelPhases{
				Phase1: true,
				Phase2: false,
				Phase3: true,
				Phase4: false,
			},
			SupportedLCSCapabilitySets: &SupportedLCSCapabilitySets{
				LcsCapabilitySet1: true,
				LcsCapabilitySet2: false,
				LcsCapabilitySet3: false,
				LcsCapabilitySet4: false,
				LcsCapabilitySet5: true,
			},
		},
	}

	encoded, err := ul.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal UpdateLocation: %v", err)
	}

	parsed, _, err := ParseUpdateLocation(encoded)
	if err != nil {
		t.Fatalf("Failed to parse UpdateLocation: %v", err)
	}

	if parsed.VlrCapability == nil {
		t.Fatal("VlrCapability is nil in parsed struct")
	}

	if parsed.VlrCapability.SupportedCamelPhases == nil {
		t.Fatal("SupportedCamelPhases is nil in parsed struct")
	}
	if !parsed.VlrCapability.SupportedCamelPhases.Phase1 {
		t.Error("Phase1 should be true")
	}
	if parsed.VlrCapability.SupportedCamelPhases.Phase2 {
		t.Error("Phase2 should be false")
	}
	if !parsed.VlrCapability.SupportedCamelPhases.Phase3 {
		t.Error("Phase3 should be true")
	}

	if parsed.VlrCapability.SupportedLCSCapabilitySets == nil {
		t.Fatal("SupportedLCSCapabilitySets is nil in parsed struct")
	}
	if !parsed.VlrCapability.SupportedLCSCapabilitySets.LcsCapabilitySet1 {
		t.Error("LcsCapabilitySet1 should be true")
	}
	if !parsed.VlrCapability.SupportedLCSCapabilitySets.LcsCapabilitySet5 {
		t.Error("LcsCapabilitySet5 should be true")
	}
}
