// Test code generated by code-agent (AI agent). DO NOT EDIT MANUALLY.
// Purpose:
// - To increase coverage
//

package gsmmap

import (
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
)

func TestMarshalErrors(t *testing.T) {
	t.Run("SriSm_InvalidMSISDN", func(t *testing.T) {
		sriSm := &SriSm{
			MSISDN: "INVALID",
		}
		_, err := sriSm.Marshal()
		if err == nil {
			t.Error("Expected error for invalid MSISDN")
		} else if !strings.Contains(err.Error(), "failed to encode MSISDN") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("SriSm_InvalidServiceCentreAddress", func(t *testing.T) {
		sriSm := &SriSm{
			MSISDN:               "12345",
			ServiceCentreAddress: "INVALID",
		}
		_, err := sriSm.Marshal()
		if err == nil {
			t.Error("Expected error for invalid ServiceCentreAddress")
		} else if !strings.Contains(err.Error(), "failed to encode ServiceCentreAddress") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("SriSmResp_InvalidIMSI", func(t *testing.T) {
		resp := &SriSmResp{
			IMSI: "INVALID",
		}
		_, err := resp.Marshal()
		if err == nil {
			t.Error("Expected error for invalid IMSI")
		} else if !strings.Contains(err.Error(), "failed to encode IMSI") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("SriSmResp_InvalidNetworkNodeNumber", func(t *testing.T) {
		resp := &SriSmResp{
			IMSI: "12345",
			LocationInfoWithLMSI: LocationInfoWithLMSI{
				NetworkNodeNumber: "INVALID",
			},
		}
		_, err := resp.Marshal()
		if err == nil {
			t.Error("Expected error for invalid NetworkNodeNumber")
		} else if !strings.Contains(err.Error(), "failed to encode NetworkNodeNumber") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("MtFsm_InvalidIMSI", func(t *testing.T) {
		mtFsm := &MtFsm{
			IMSI: "INVALID",
		}
		_, err := mtFsm.Marshal()
		if err == nil {
			t.Error("Expected error for invalid IMSI")
		} else if !strings.Contains(err.Error(), "failed to encode IMSI") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("MtFsm_InvalidServiceCentreAddressOA", func(t *testing.T) {
		mtFsm := &MtFsm{
			IMSI:                   "12345",
			ServiceCentreAddressOA: "INVALID",
		}
		_, err := mtFsm.Marshal()
		if err == nil {
			t.Error("Expected error for invalid ServiceCentreAddressOA")
		} else if !strings.Contains(err.Error(), "failed to encode ServiceCentreAddressOA") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("MoFsm_InvalidServiceCentreAddressDA", func(t *testing.T) {
		moFsm := &MoFsm{
			ServiceCentreAddressDA: "INVALID",
		}
		_, err := moFsm.Marshal()
		if err == nil {
			t.Error("Expected error for invalid ServiceCentreAddressDA")
		} else if !strings.Contains(err.Error(), "failed to encode ServiceCentreAddressDA") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("MoFsm_InvalidMSISDN", func(t *testing.T) {
		moFsm := &MoFsm{
			ServiceCentreAddressDA: "12345",
			MSISDN:                 "INVALID",
		}
		_, err := moFsm.Marshal()
		if err == nil {
			t.Error("Expected error for invalid MSISDN")
		} else if !strings.Contains(err.Error(), "failed to encode MSISDN") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("UpdateLocation_InvalidIMSI", func(t *testing.T) {
		ul := &UpdateLocation{
			IMSI: "INVALID",
		}
		_, err := ul.Marshal()
		if err == nil {
			t.Error("Expected error for invalid IMSI")
		} else if !strings.Contains(err.Error(), "failed to encode IMSI") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("UpdateLocation_InvalidMSCNumber", func(t *testing.T) {
		ul := &UpdateLocation{
			IMSI:      "12345",
			MSCNumber: "INVALID",
		}
		_, err := ul.Marshal()
		if err == nil {
			t.Error("Expected error for invalid MSCNumber")
		} else if !strings.Contains(err.Error(), "failed to encode MSCNumber") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("UpdateLocation_InvalidVLRNumber", func(t *testing.T) {
		ul := &UpdateLocation{
			IMSI:      "12345",
			MSCNumber: "12345",
			VLRNumber: "INVALID",
		}
		_, err := ul.Marshal()
		if err == nil {
			t.Error("Expected error for invalid VLRNumber")
		} else if !strings.Contains(err.Error(), "failed to encode VLRNumber") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("UpdateGprsLocation_InvalidIMSI", func(t *testing.T) {
		ugl := &UpdateGprsLocation{
			IMSI: "INVALID",
		}
		_, err := ugl.Marshal()
		if err == nil {
			t.Error("Expected error for invalid IMSI")
		} else if !strings.Contains(err.Error(), "failed to encode IMSI") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("UpdateGprsLocation_InvalidSGSNNumber", func(t *testing.T) {
		ugl := &UpdateGprsLocation{
			IMSI:       "12345",
			SGSNNumber: "INVALID",
		}
		_, err := ugl.Marshal()
		if err == nil {
			t.Error("Expected error for invalid SGSNNumber")
		} else if !strings.Contains(err.Error(), "failed to encode SGSNNumber") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("UpdateGprsLocation_InvalidSGSNAddress", func(t *testing.T) {
		ugl := &UpdateGprsLocation{
			IMSI:        "12345",
			SGSNNumber:  "12345",
			SGSNAddress: "INVALID-IP",
		}
		_, err := ugl.Marshal()
		if err == nil {
			t.Error("Expected error for invalid SGSNAddress")
		} else if !strings.Contains(err.Error(), "failed to encode SGSNAddress") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("UpdateLocationRes_InvalidHLRNumber", func(t *testing.T) {
		res := &UpdateLocationRes{
			HLRNumber: "INVALID",
		}
		_, err := res.Marshal()
		if err == nil {
			t.Error("Expected error for invalid HLRNumber")
		} else if !strings.Contains(err.Error(), "failed to encode HLRNumber") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})

	t.Run("UpdateGprsLocationRes_InvalidHLRNumber", func(t *testing.T) {
		res := &UpdateGprsLocationRes{
			HLRNumber: "INVALID",
		}
		_, err := res.Marshal()
		if err == nil {
			t.Error("Expected error for invalid HLRNumber")
		} else if !strings.Contains(err.Error(), "failed to encode HLRNumber") {
			t.Errorf("Unexpected error message: %v", err)
		}
	})
}

func TestUpdateLocationMarshal_WithVlrCapability(t *testing.T) {
	ul := &UpdateLocation{
		IMSI:      "123456789012345",
		MSCNumber: "12345",
		VLRNumber: "67890",
		VlrCapability: &VlrCapability{
			SupportedCamelPhases: &SupportedCamelPhases{
				Phase1: true,
				Phase2: false,
				Phase3: true,
				Phase4: false,
			},
			SupportedLCSCapabilitySets: &SupportedLCSCapabilitySets{
				LcsCapabilitySet1: true,
				LcsCapabilitySet2: false,
				LcsCapabilitySet3: false,
				LcsCapabilitySet4: false,
				LcsCapabilitySet5: true,
			},
		},
	}

	encoded, err := ul.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal UpdateLocation: %v", err)
	}

	parsed, _, err := ParseUpdateLocation(encoded)
	if err != nil {
		t.Fatalf("Failed to parse UpdateLocation: %v", err)
	}

	if parsed.VlrCapability == nil {
		t.Fatal("VlrCapability is nil in parsed struct")
	}

	if parsed.VlrCapability.SupportedCamelPhases == nil {
		t.Fatal("SupportedCamelPhases is nil in parsed struct")
	}
	if !parsed.VlrCapability.SupportedCamelPhases.Phase1 {
		t.Error("Phase1 should be true")
	}
	if parsed.VlrCapability.SupportedCamelPhases.Phase2 {
		t.Error("Phase2 should be false")
	}
	if !parsed.VlrCapability.SupportedCamelPhases.Phase3 {
		t.Error("Phase3 should be true")
	}

	if parsed.VlrCapability.SupportedLCSCapabilitySets == nil {
		t.Fatal("SupportedLCSCapabilitySets is nil in parsed struct")
	}
	if !parsed.VlrCapability.SupportedLCSCapabilitySets.LcsCapabilitySet1 {
		t.Error("LcsCapabilitySet1 should be true")
	}
	if !parsed.VlrCapability.SupportedLCSCapabilitySets.LcsCapabilitySet5 {
		t.Error("LcsCapabilitySet5 should be true")
	}
}

func TestAnyTimeInterrogationRoundTrip_IMSI(t *testing.T) {
	ati := &AnyTimeInterrogation{
		SubscriberIdentity: SubscriberIdentity{IMSI: "123456789012345"},
		RequestedInfo:      RequestedInfo{LocationInformation: true, SubscriberState: true},
		GsmSCFAddress:      "1234567890",
	}

	marshaledBytes, err := ati.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal AnyTimeInterrogation: %v", err)
	}

	parsed, _, err := ParseAnyTimeInterrogationDER(marshaledBytes)
	if err != nil {
		t.Fatalf("Failed to parse AnyTimeInterrogation: %v", err)
	}

	if diff := cmp.Diff(ati, parsed); diff != "" {
		t.Errorf("Round-trip mismatch (-original +parsed):\n%s", diff)
	}
}

func TestAnyTimeInterrogationRoundTrip_MSISDN(t *testing.T) {
	ati := &AnyTimeInterrogation{
		SubscriberIdentity: SubscriberIdentity{MSISDN: "962260853818"},
		RequestedInfo:      RequestedInfo{LocationInformation: true, CurrentLocation: true},
		GsmSCFAddress:      "1234567890",
	}

	marshaledBytes, err := ati.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal AnyTimeInterrogation: %v", err)
	}

	parsed, _, err := ParseAnyTimeInterrogationDER(marshaledBytes)
	if err != nil {
		t.Fatalf("Failed to parse AnyTimeInterrogation: %v", err)
	}

	if diff := cmp.Diff(ati, parsed); diff != "" {
		t.Errorf("Round-trip mismatch (-original +parsed):\n%s", diff)
	}
}

func TestAnyTimeInterrogationRoundTrip_AllFlags(t *testing.T) {
	psDomain := PsDomain
	ati := &AnyTimeInterrogation{
		SubscriberIdentity: SubscriberIdentity{IMSI: "123456789012345"},
		RequestedInfo: RequestedInfo{
			LocationInformation:             true,
			SubscriberState:                 true,
			CurrentLocation:                 true,
			RequestedDomain:                 &psDomain,
			IMEI:                            true,
			MsClassmark:                     true,
			MnpRequestedInfo:                true,
			LocationInformationEPSSupported: true,
			TAdsData:                        true,
			RequestedNodes:                  &RequestedNodes{MME: true, SGSN: true},
			ServingNodeIndication:           true,
			LocalTimeZoneRequest:            true,
		},
		GsmSCFAddress: "1234567890",
	}

	marshaledBytes, err := ati.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal AnyTimeInterrogation: %v", err)
	}

	parsed, _, err := ParseAnyTimeInterrogationDER(marshaledBytes)
	if err != nil {
		t.Fatalf("Failed to parse AnyTimeInterrogation: %v", err)
	}

	if diff := cmp.Diff(ati, parsed); diff != "" {
		t.Errorf("Round-trip mismatch (-original +parsed):\n%s", diff)
	}
}

func TestAnyTimeInterrogationRoundTrip_CsDomain(t *testing.T) {
	csDomain := CsDomain
	ati := &AnyTimeInterrogation{
		SubscriberIdentity: SubscriberIdentity{IMSI: "123456789012345"},
		RequestedInfo:      RequestedInfo{LocationInformation: true, RequestedDomain: &csDomain},
		GsmSCFAddress:      "1234567890",
	}

	marshaledBytes, err := ati.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal AnyTimeInterrogation: %v", err)
	}

	parsed, _, err := ParseAnyTimeInterrogationDER(marshaledBytes)
	if err != nil {
		t.Fatalf("Failed to parse AnyTimeInterrogation: %v", err)
	}

	if diff := cmp.Diff(ati, parsed); diff != "" {
		t.Errorf("Round-trip mismatch (-original +parsed):\n%s", diff)
	}
}

func TestAnyTimeInterrogationRoundTrip_RequestedNodesMMEOnly(t *testing.T) {
	ati := &AnyTimeInterrogation{
		SubscriberIdentity: SubscriberIdentity{IMSI: "123456789012345"},
		RequestedInfo:      RequestedInfo{LocationInformation: true, RequestedNodes: &RequestedNodes{MME: true, SGSN: false}},
		GsmSCFAddress:      "1234567890",
	}

	marshaledBytes, err := ati.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal AnyTimeInterrogation: %v", err)
	}

	parsed, _, err := ParseAnyTimeInterrogationDER(marshaledBytes)
	if err != nil {
		t.Fatalf("Failed to parse AnyTimeInterrogation: %v", err)
	}

	if diff := cmp.Diff(ati, parsed); diff != "" {
		t.Errorf("Round-trip mismatch (-original +parsed):\n%s", diff)
	}
}

func TestAnyTimeInterrogationMarshal_ValidationError_NoIdentity(t *testing.T) {
	ati := &AnyTimeInterrogation{
		RequestedInfo: RequestedInfo{LocationInformation: true},
		GsmSCFAddress: "1234567890",
	}

	_, err := ati.Marshal()
	if err == nil {
		t.Fatal("Expected error when neither IMSI nor MSISDN is set")
	}
}

func TestAnyTimeInterrogationMarshal_ValidationError_BothIdentities(t *testing.T) {
	ati := &AnyTimeInterrogation{
		SubscriberIdentity: SubscriberIdentity{IMSI: "123456789012345", MSISDN: "962260853818"},
		RequestedInfo:      RequestedInfo{LocationInformation: true},
		GsmSCFAddress:      "1234567890",
	}

	_, err := ati.Marshal()
	if err == nil {
		t.Fatal("Expected error when both IMSI and MSISDN are set")
	}
}

func TestAnyTimeInterrogationRoundTrip_MinimalFlags(t *testing.T) {
	ati := &AnyTimeInterrogation{
		SubscriberIdentity: SubscriberIdentity{IMSI: "123456789012345"},
		GsmSCFAddress:      "1234567890",
	}

	marshaledBytes, err := ati.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal AnyTimeInterrogation: %v", err)
	}

	parsed, _, err := ParseAnyTimeInterrogationDER(marshaledBytes)
	if err != nil {
		t.Fatalf("Failed to parse AnyTimeInterrogation: %v", err)
	}

	if diff := cmp.Diff(ati, parsed); diff != "" {
		t.Errorf("Round-trip mismatch (-original +parsed):\n%s", diff)
	}
}
