package asn1mapmodel

// OperationLocalValue
// GSMMAPOperationLocalvalue
// Operation Code , opcode

type OpCode int

const (
	UpdateLocation OpCode = iota + 2
	CancelLocation
	ProvideRoamingNumber
	NoteSubscriberDataModified
	ResumeCallHandling
	InsertSubscriberData
	DeleteSubscriberData
	SendParameters
	RegisterSS
	EraseSS
	ActivateSS
	DeactivateSS
	InterrogateSS
	AuthenticationFailureReport
	NotifySS
	RegisterPassword
	GetPassword
	ProcessUnstructuredSSData
	ReleaseResources
	MtForwardSMVGCS
	SendRoutingInfo
	UpdateGprsLocation
	SendRoutingInfoForGprs
	FailureReport
	NoteMsPresentForGprs
	UnAllocated27
	PerformHandover
	SendEndSignal
	PerformSubsequentHandover
	ProvideSIWFSNumber
	SIWFSFSSignallingModify
	ProcessAccessSignalling
	ForwardAccessSignalling
	NoteInternalHandover
	CancelVcsgLocation
	Reset
	ForwardCheckSS
	PrepareGroupCall
	SendGroupCallEndSignal
	ProcessGroupCallSignalling
	ForwardGroupCallSignalling
	CheckIMEI
	MtForwardSM
	SendRoutingInfoForSM
	MoForwardSM
	ReportSMDeliveryStatus
	NoteSubscriberPresent
	AlertServiceCentreWithoutResult
	ActivateTraceMode
	DeactivateTraceMode
	TraceSubscriberActivity
	UpdateVcsgLocation
	BeginSubscriberActivity
	SendIdentification
	SendAuthenticationInfo
	RestoreData
	SendIMSI
	ProcessUnstructuredSSRequest
	UnstructuredSSRequest
	UnstructuredSSNotify
	AnyTimeSubscriptionInterrogation
	InformServiceCentre
	AlertServiceCentre
	AnyTimeModification
	ReadyForSM
	PurgeMS
	PrepareHandover
	PrepareSubsequentHandover
	ProvideSubscriberInfo
	AnyTimeInterrogation
	SSInvocationNotification
	SetReportingState
	StatusReport
	RemoteUserFree
	RegisterCCEntry
	EraseCCEntry
	SecureTransportClass1
	SecureTransportClass2
	SecureTransportClass3
	SecureTransportClass4
	UnAllocated82
	ProvideSubscriberLocation
	SendGroupCallInfo
	SendRoutingInfoForLCS
	SubscriberLocationReport
	IstAlert
	IstCommand
	NoteMMEvent
	UnAllocated90
	UnAllocated91
	UnAllocated92
	UnAllocated93
	UnAllocated94
	UnAllocated95
	UnAllocated96
	UnAllocated97
	UnAllocated98
	UnAllocated99
	UnAllocated100
	UnAllocated101
	UnAllocated102
	UnAllocated103
	UnAllocated104
	UnAllocated105
	UnAllocated106
	UnAllocated107
	UnAllocated108
	LcsPeriodicLocationCancellation
	LcsLocationUpdate
	LcsPeriodicLocationRequest
	LcsAreaEventCancellation
	LcsAreaEventReport
	LcsAreaEventRequest
	LcsMOLR
	LcsLocationNotification
	CallDeflection
	UserUserService
	AccessRegisterCCEntry
	ForwardCUGInfo
	SplitMPTY
	RetrieveMPTY
	HoldMPTY
	BuildMPTY
	ForwardChargeAdvice
	ExplicitCT
)
