// Test code generated by code-agent (AI agent). DO NOT EDIT MANUALLY.
// Purpose:
// - To increase coverage
//

package asn1mapmodel

import (
	"bytes"
	"testing"

	"github.com/gomaja/go-gsmmap/utils"
)

func TestAddressStringHelpers(t *testing.T) {
	// Test EncodeAddressString and DecodeAddressString
	digits, err := utils.EncodeTBCDDigits("123456")
	if err != nil {
		t.Fatal(err)
	}
	ext := uint8(ExtensionNo)
	nature := uint8(AddressNatureInternational)
	plan := uint8(NumberingPlanISDN)

	encoded := EncodeAddressString(ext, nature, plan, digits)

	gotExt, gotNature, gotPlan, gotDigits := DecodeAddressString(encoded)

	if gotExt != ext {
		t.Errorf("Extension mismatch: want %v, got %v", ext, gotExt)
	}
	if gotNature != nature {
		t.Errorf("Nature mismatch: want %v, got %v", nature, gotNature)
	}
	if gotPlan != plan {
		t.Errorf("Plan mismatch: want %v, got %v", plan, gotPlan)
	}
	if !bytes.Equal(gotDigits, digits) {
		t.Errorf("Digits mismatch: want %v, got %v", digits, gotDigits)
	}

	// Test DecodeAddressString with empty input
	e, n, p, d := DecodeAddressString(nil)
	if e != 0 || n != 0 || p != 0 || d != nil {
		t.Errorf("Expected zero values for empty input, got %v %v %v %v", e, n, p, d)
	}
}

func TestUpdateLocationArgHelpers(t *testing.T) {
	imsiStr := "123456789012345"
	imsiBytes, err := utils.EncodeTBCDDigits(imsiStr)
	if err != nil {
		t.Fatal(err)
	}

	mscStr := "9876543210"
	mscBytes, err := utils.EncodeTBCDDigits(mscStr)
	if err != nil {
		t.Fatal(err)
	}
	mscAddr := EncodeAddressString(ExtensionNo, AddressNatureInternational, NumberingPlanISDN, mscBytes)

	vlrStr := "1122334455"
	vlrBytes, err := utils.EncodeTBCDDigits(vlrStr)
	if err != nil {
		t.Fatal(err)
	}
	vlrAddr := EncodeAddressString(ExtensionNo, AddressNatureInternational, NumberingPlanISDN, vlrBytes)

	arg := &UpdateLocationArg{
		IMSI:      IMSI(imsiBytes),
		MSCNumber: ISDNAddressString(mscAddr),
		VLRNumber: ISDNAddressString(vlrAddr),
	}

	if s, err := arg.GetImsiString(); err != nil || s != imsiStr {
		t.Errorf("GetImsiString: want %s, got %s (err: %v)", imsiStr, s, err)
	}

	if s, err := arg.GetMSCNumberString(); err != nil || s != mscStr {
		t.Errorf("GetMSCNumberString: want %s, got %s (err: %v)", mscStr, s, err)
	}

	if s, err := arg.GetVLRNumberString(); err != nil || s != vlrStr {
		t.Errorf("GetVLRNumberString: want %s, got %s (err: %v)", vlrStr, s, err)
	}
}

func TestUpdateGprsLocationArgHelpers(t *testing.T) {
	imsiStr := "123456789012345"
	imsiBytes, err := utils.EncodeTBCDDigits(imsiStr)
	if err != nil {
		t.Fatal(err)
	}

	sgsnStr := "9876543210"
	sgsnBytes, err := utils.EncodeTBCDDigits(sgsnStr)
	if err != nil {
		t.Fatal(err)
	}
	sgsnAddr := EncodeAddressString(ExtensionNo, AddressNatureInternational, NumberingPlanISDN, sgsnBytes)

	sgsnIp := "192.168.1.1"
	sgsnIpBytes, err := utils.BuildGSNAddress(sgsnIp)
	if err != nil {
		t.Fatal(err)
	}

	arg := &UpdateGprsLocationArg{
		IMSI:        IMSI(imsiBytes),
		SGSNNumber:  ISDNAddressString(sgsnAddr),
		SGSNAddress: GSNAddress(sgsnIpBytes),
	}

	if s, err := arg.GetImsiString(); err != nil || s != imsiStr {
		t.Errorf("GetImsiString: want %s, got %s (err: %v)", imsiStr, s, err)
	}

	if s, err := arg.GetSGSNNumberString(); err != nil || s != sgsnStr {
		t.Errorf("GetSGSNNumberString: want %s, got %s (err: %v)", sgsnStr, s, err)
	}

	if s, err := arg.GetSGSNAddressString(); err != nil || s != sgsnIp {
		t.Errorf("GetSGSNAddressString: want %s, got %s (err: %v)", sgsnIp, s, err)
	}
}

func TestUpdateLocationResHelpers(t *testing.T) {
	hlrStr := "5566778899"
	hlrBytes, err := utils.EncodeTBCDDigits(hlrStr)
	if err != nil {
		t.Fatal(err)
	}
	hlrAddr := EncodeAddressString(ExtensionNo, AddressNatureInternational, NumberingPlanISDN, hlrBytes)

	res := &UpdateLocationRes{
		HLRNumber: ISDNAddressString(hlrAddr),
	}

	if s, err := res.GetHLRNumberString(); err != nil || s != hlrStr {
		t.Errorf("GetHLRNumberString: want %s, got %s (err: %v)", hlrStr, s, err)
	}
}

func TestUpdateGprsLocationResHelpers(t *testing.T) {
	hlrStr := "9988776655"
	hlrBytes, err := utils.EncodeTBCDDigits(hlrStr)
	if err != nil {
		t.Fatal(err)
	}
	hlrAddr := EncodeAddressString(ExtensionNo, AddressNatureInternational, NumberingPlanISDN, hlrBytes)

	res := &UpdateGprsLocationRes{
		HLRNumber: ISDNAddressString(hlrAddr),
	}

	if s, err := res.GetHLRNumberString(); err != nil || s != hlrStr {
		t.Errorf("GetHLRNumberString: want %s, got %s (err: %v)", hlrStr, s, err)
	}
}

func TestGetErrorString(t *testing.T) {
	// Known error
	known := GetErrorString(uint8(ErrorUnknownSubscriber))
	if known != "UnknownSubscriber" {
		t.Errorf("GetErrorString(1): want UnknownSubscriber, got %s", known)
	}

	// Unknown error
	unknown := GetErrorString(255)
	expectedPrefix := "Error code not define in"
	if len(unknown) < len(expectedPrefix) || unknown[:len(expectedPrefix)] != expectedPrefix {
		t.Errorf("GetErrorString(255): want message starting with '%s', got '%s'", expectedPrefix, unknown)
	}
}

func TestRoutingInfoForSMHelpers(t *testing.T) {
	msisdnStr := "1234567890"
	msisdnBytes, err := utils.EncodeTBCDDigits(msisdnStr)
	if err != nil {
		t.Fatal(err)
	}
	msisdnAddr := EncodeAddressString(ExtensionNo, AddressNatureInternational, NumberingPlanISDN, msisdnBytes)

	scaStr := "0987654321"
	scaBytes, err := utils.EncodeTBCDDigits(scaStr)
	if err != nil {
		t.Fatal(err)
	}
	scaAddr := EncodeAddressString(ExtensionNo, AddressNatureInternational, NumberingPlanISDN, scaBytes)

	arg := &RoutingInfoForSMArg{
		MSISDN:               ISDNAddressString(msisdnAddr),
		ServiceCentreAddress: AddressString(scaAddr),
	}

	if s, err := arg.GetMsisdnString(); err != nil || s != msisdnStr {
		t.Errorf("GetMsisdnString: want %s, got %s (err: %v)", msisdnStr, s, err)
	}

	if s, err := arg.GetServiceCenterAddressString(); err != nil || s != scaStr {
		t.Errorf("GetServiceCenterAddressString: want %s, got %s (err: %v)", scaStr, s, err)
	}

	imsiStr := "1122334455"
	imsiBytes, err := utils.EncodeTBCDDigits(imsiStr)
	if err != nil {
		t.Fatal(err)
	}

	nnnStr := "5544332211"
	nnnBytes, err := utils.EncodeTBCDDigits(nnnStr)
	if err != nil {
		t.Fatal(err)
	}
	nnnAddr := EncodeAddressString(ExtensionNo, AddressNatureInternational, NumberingPlanISDN, nnnBytes)

	res := &RoutingInfoForSMRes{
		IMSI: IMSI(imsiBytes),
		LocationInfoWithLMSI: LocationInfoWithLMSI{
			NetworkNodeNumber: ISDNAddressString(nnnAddr),
		},
	}

	if s, err := res.GetImsiString(); err != nil || s != imsiStr {
		t.Errorf("GetImsiString: want %s, got %s (err: %v)", imsiStr, s, err)
	}

	if s, err := res.GetNetworkNodeNumberString(); err != nil || s != nnnStr {
		t.Errorf("GetNetworkNodeNumberString: want %s, got %s (err: %v)", nnnStr, s, err)
	}
}

func TestSMHelpers(t *testing.T) {
	// SMRPDA
	imsiStr := "9988776655"
	imsiBytes, err := utils.EncodeTBCDDigits(imsiStr)
	if err != nil {
		t.Fatal(err)
	}

	scdaStr := "5566778899"
	scdaBytes, err := utils.EncodeTBCDDigits(scdaStr)
	if err != nil {
		t.Fatal(err)
	}
	scdaAddr := EncodeAddressString(ExtensionNo, AddressNatureInternational, NumberingPlanISDN, scdaBytes)

	da := &SMRPDA{
		IMSI:                   IMSI(imsiBytes),
		ServiceCentreAddressDA: AddressString(scdaAddr),
	}

	if s, err := da.GetImsiString(); err != nil || s != imsiStr {
		t.Errorf("SMRPDA.GetImsiString: want %s, got %s (err: %v)", imsiStr, s, err)
	}

	if s, err := da.GetServiceCentreAddressDAString(); err != nil || s != scdaStr {
		t.Errorf("SMRPDA.GetServiceCentreAddressDAString: want %s, got %s (err: %v)", scdaStr, s, err)
	}

	// SMRPOA
	msisdnStr := "4433221100"
	msisdnBytes, err := utils.EncodeTBCDDigits(msisdnStr)
	if err != nil {
		t.Fatal(err)
	}
	msisdnAddr := EncodeAddressString(ExtensionNo, AddressNatureInternational, NumberingPlanISDN, msisdnBytes)

	scoaStr := "0011223344"
	scoaBytes, err := utils.EncodeTBCDDigits(scoaStr)
	if err != nil {
		t.Fatal(err)
	}
	scoaAddr := EncodeAddressString(ExtensionNo, AddressNatureInternational, NumberingPlanISDN, scoaBytes)

	oa := &SMRPOA{
		MSISDN:                 ISDNAddressString(msisdnAddr),
		ServiceCentreAddressOA: AddressString(scoaAddr),
	}

	if s, err := oa.GetMsisdnString(); err != nil || s != msisdnStr {
		t.Errorf("SMRPOA.GetMsisdnString: want %s, got %s (err: %v)", msisdnStr, s, err)
	}

	if s, err := oa.GetServiceCentreAddressOAString(); err != nil || s != scoaStr {
		t.Errorf("SMRPOA.GetServiceCentreAddressOAString: want %s, got %s (err: %v)", scoaStr, s, err)
	}
}
